source 'https://rubygems.org'

gem 'rails', '3.2.2'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer'

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
gem 'devise'
gem 'refinerycms-core', '2.0.2'
gem 'refinerycms-dashboard', '2.0.2'
gem 'refinerycms-images', '2.0.2'
gem 'refinerycms-pages', '2.0.2'
gem 'refinerycms-resources', '2.0.2'
#gem "refinerycms-authentication", "2.0.2"
#gem "refinerycms-blog"
#gem 'refinerycms-settings',   :git => 'git://github.com/resolve/refinerycms.git'
#gem 'refinerycms-generators', :git => 'git://github.com/resolve/refinerycms-generators.git'
